### ISSUE TITLE
Collapsibles button on facelessui.com

### ISSUE THREAD

**Issue by JuliusGudni** [trouble/react-collapsibles#21]
The collapsibles button on https://facelessui.com/ links to /docs/collapsible, which routes to a 404 error, and should link to /docs/collapsibles, which is the correct route.
Would be great to have the web frontend in a public repo to be able to contribute to that.

**Comment by jacobsfletch** [comment]
Hi @JuliusGudni. Good catch! The repo for the website is in fact public, and can be found [here](https://github.com/jacobsfletch/facelessui.com). The reason it is not nested under the Faceless UI org is to avoid Vercel hosting fees. PR's are happily accepted, or otherwise we'll be sure to take care of being that it's front-facing. Thank you!

**Comment by jacobsfletch** [comment]
Hey @JuliusGudni I went ahead and took care of that broken link [with this commit](https://github.com/jacobsfletch/facelessui.com/commit/17612733f6b775deb06b2b28b44067070500f320). Thanks again for heads up. Keep it coming!

**Comment by JuliusGudni** [comment]
Hey @jacobsfletch. That makes sense, and thank you for the nice and welcoming response. I would have submitted a PR, but somehow I missed the email notification and didn't see your response until now.
I'd love to contribute on this project and I have some ideas. Is there some way I can contact you, everything's fine with me, Slack, Discord, Email... or whatever you prefer ;)

**Comment by jacobsfletch** [comment]
@JuliusGudni absolutely, my email is `jacobsfletch@gmail.com` or `dev@facelessui.com`. I'm on Slack too.
