### ISSUE TITLE
Opt-out of cloneElement for clickableNode

### ISSUE THREAD

**Issue by jacobsfletch** [trouble/react-collapsibles#4]
This function restricts the method by which the clickable node is injected. A wrapping DOM element is a small but necessary compromise.

**Comment by jacobsfletch** [comment]
We could try and deprecate the `collapsibles` prop entirely, and allow the component to accept instances of `Collapsible` directly -- which might improves composition for the end user. The cloned props just need to take less precedence than the inject props inbound from the `CollapsibleGroup`

**Comment by JarrodMFlesch** [comment]
NOTE: I am not sure if what I about to say is what the issue title is saying exactly so I am just looking for clarification on the issue pulled here.

Recently when working on a project - I needed to nest the clickable node, but with the current api I was not able to accomplish this as a `<Collapsible />` wraps the header and body into one.

Example:
```html
<div class="collapsible">
  <div class="collapsible__header">
    <p>Title Text</p>
    <div>
      <div class="collapsible__header__controls">
        {/* the only element that should trigger a collapse */}
        <div class="collapsible__header__trigger" />
        <div class="collapsible__header__action-button-1" />
        <div class="collapsible__header__action-button-2" />
      </div>
    </div>
  </div>

  <div class="collapsible__content">
    <p>the collapsible content</p>
  </div>
</div>
```

I was thinking - a `<Collapsible />` could be a HOC that passes props down, one of them being a ref that could be placed onto an element and only that element would be responsible for handling the trigger, instead of an entire clickable node. 

Would probably need to pass a ref down for the content as well, to know what to open/close.


When implemented, it would look something _like_ below:
```html
<Collapsible>
  {(collapsibleProps) => {
    return (
      <div className="collapsible">
        <div className="collapsible__header">
          <p>Title Text</p>

          <div>
            <div className="collapsible__header__controls">
              {/* the only element that should trigger a collapse */}
              <div className="collapsible__header__trigger" ref={collapsibleProps.triggerRef} />
              <div className="collapsible__header__action-button-1" />
              <div className="collapsible__header__action-button-2" />
            </div>
          </div>
        </div>

        <div className="collapsible__content" ref={collapsibleProps.contentRef}>
          <p>the content to collapse.</p>
        </div>
      </div>
    );
  }}
</Collapsible>
```

Would love to discuss!
